### ISSUE TITLE
About the .ps file 

### ISSUE THREAD

**Issue by ShenyangTang** [MikeAxtell/strucVis#3]
Hello Mike,
I have successfully used strucVis to make predictions of structure, but when I looked at the .ps file, I found that there was no color annotation about the depth of coverage, only black letters. This matter bothers me very much. I hope you can give me some answers. 
At the same time, I also want to ask, if I want to use this software, how can I quote it?Thank you very much!
Wish you good luck.

**Comment by MikeAxtell** [comment]
Can you post the stdout and stderr of the job , and also post the resulting post-script file (or email it to me at ***@***.***)?

From: ShenyangTang ***@***.***>
Date: Tuesday, December 13, 2022 at 4:33 AM
To: MikeAxtell/strucVis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MikeAxtell/strucVis] About the .ps file (Issue #3)

Hello Mike,
I have successfully used strucVis to make predictions of structure, but when I looked at the .ps file, I found that there was no color annotation about the depth of coverage, only black letters. This matter bothers me very much. I hope you can give me some answers. Thank you very much!
Wish you good luck.

**Comment by ShenyangTang** [comment]
OK, I'm already emailed it to you at mja18@psu.edu. Thank you so much!
